name: AppidQuick

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Clone Repository
          uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.10' 

        - name: Get Appid
          run: |
            python -m pip install frida
            python GetAppid.py